### PR TITLE
Fix timeseries.crop method and add tests + highlighter plugin naming convention

### LINKED ISSUE #83: TimeSeries.crop slices to incorrect indexes
`TimeSeries.crop` uses bisect to find the events, then slices to those indexes. Since bisect goes to the event PRIOR to the passed timestamp, this can result in an event preceding the specified timerange being included, as well as the final event in the specified timerange being excluded. This is very obvious when trying to crop a sparse events list, where things seriously outside of your range can show up.

Here are 4 examples, one using exact timestamps, where the behavior is arguably correct, and 3 with timestamps not exactly matching events, where it seems pretty clearly wrong.

I'd expect value 4 to be included here
```js
var ts1 = new _pondjs.TimeSeries({
  name: 'exact timestamps',
  columns: ['time', 'value'],
  points: [[1504014065242,1],[1504014065243,2],[1504014065244,3],[1504014065245,4],[1504014065246,5]]
})

var ts2 = ts1.crop(new _pondjs.TimeRange([1504014065243,1504014065245]))
ts2.toJSON().points
// [[1504014065243,2],[1504014065244,3]]
```

I'd expect value 1 to NOT be included (and value 4 to be included)
```js
var ts1 = new _pondjs.TimeSeries({
  name: 'initial timestamp non-match',
  columns: ['time', 'value'],
  points: [[1504014065240,1],[1504014065243,2],[1504014065244,3],[1504014065245,4],[1504014065246,5]]
})

var ts2 = ts1.crop(new _pondjs.TimeRange([1504014065242,1504014065245]))
ts2.toJSON().points
// [[1504014065240,1],[1504014065243,2],[1504014065244,3]
```

I'd expect value 4 to be included
```js
var ts1 = new _pondjs.TimeSeries({
  name: 'final timestamp non-match',
  columns: ['time', 'value'],
  points: [[1504014065240,1],[1504014065243,2],[1504014065244,3],[1504014065245,4],[1504014065249,5]]
})

var ts2 = ts1.crop(new _pondjs.TimeRange([1504014065243,1504014065247]))
ts2.toJSON().points
// [[1504014065243,2],[1504014065244,3]
```

I'd expect value 1 to NOT be included (and value 4 to be included)
```js
var ts1 = new _pondjs.TimeSeries({
  name: 'both timestamp non-match',
  columns: ['time', 'value'],
  points: [[1504014065240,1],[1504014065243,2],[1504014065244,3],[1504014065245,4],[1504014065249,5]]
})

var ts2 = ts1.crop(new _pondjs.TimeRange([1504014065242,1504014065247]))
ts2.toJSON().points
// [[1504014065240,1],[1504014065243,2],[1504014065244,3]
```

I'm going to take a stab at submitting a PR for this right now.

### PR DESCRIPTION
**Pull request by sartaj10**
Fix #83 and add tests

### CODE REVIEW

**Comment by pjm17971** [comment]
I think it probably should go the other way, since Highlighter is a component, right? So by convention it probably should start with a capital letter.

**Comment by sartaj10** [comment]
@pjm17971 Just noticed that there's 2 Highlighter.js files. One in src/website/api/Highlighter.js and the other in src/website/components/Highlighter.js
Both have the same code as well. Should I just delete the one in the components folder?

**Comment by sartaj10** [comment]
Done. Should I go ahead and merge this? @pjm17971

**Comment by pjm17971** [comment]
Can you add this to the typescript branch as well?

**Comment by sartaj10** [comment]
Yes, will do that.

**Pull request merged**
